name: color_tweened
description: Widgets that change colors during a duration
homepage: https://github.com/erayerdin/color_tweened
issue_tracker: https://github.com/erayerdin/color_tweened/issues/
repository: https://github.com/erayerdin/color_tweened
version: 0.2.0

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
